name: Build .NET (Windows)
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore
        run: dotnet restore app/dotnet/MyApp/MyApp.csproj
      - name: Build
        run: dotnet build app/dotnet/MyApp/MyApp.csproj -c Release --no-restore
      - name: Publish
        run: dotnet publish app/dotnet/MyApp/MyApp.csproj -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true -o out/win-x64
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: myapp-win-x64
          path: out/win-x64/**