name: Release
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  release:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Publish
        run: |
          dotnet publish app/dotnet/MyApp/MyApp.csproj -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true -o out/win-x64
          powershell Compress-Archive -Path out/win-x64/* -DestinationPath MyApp-win-x64.zip -Force
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: MyApp-win-x64.zip
          generate_release_notes: true